const axios = require('axios');
const config = require('../config');

// Forbidden AI buzzwords and robotic phrases to audit against
const BANNED_AI_WORDS = [
  'delve', 'delving', 'testament', 'crucial', 'pivotal', 'leverage', 'leveraging',
  'furthermore', 'moreover', 'in conclusion', 'beacon', 'unwavering', 'tapestry',
  'plethora', 'navigate', 'seamlessly', 'embark', 'realm', 'harness', 'transformative'
];

/**
 * Build the system prompt designed specifically to make LLM output look 100% human-crafted
 */
function buildHumanizerSystemPrompt(profile, researchFindings, toneStyle = 'direct_natural') {
  const bannedList = BANNED_AI_WORDS.join(', ');

  let styleGuidance = '';
  switch (toneStyle) {
    case 'concise_executive':
      styleGuidance = 'Write very concisely. Punchy, factual, executive brevity. No unnecessary words or explanations.';
      break;
    case 'conversational':
      styleGuidance = 'Write in a warm, authentic, natural first-person conversational tone. Like an experienced founder speaking candidly.';
      break;
    case 'formal':
      styleGuidance = 'Professional and legally precise, but grounded. Avoid boilerplate fluff.';
      break;
    case 'direct_natural':
    default:
      styleGuidance = 'Natural, direct, everyday professional English. Varied sentence lengths. Authentic and straightforward.';
      break;
  }

  return `You are an experienced human applicant completing an official commercial application or form. 

CRITICAL DIRECTIVE: The responses MUST NOT look like they were generated by an AI assistant.
1. ABSOLUTELY NEVER use any of these dead giveaways or robotic AI clichés: [${bannedList}].
2. For specific fields (names, emails, phone numbers, addresses, EIN numbers, amounts, dropdown options): return ONLY the exact value, without any markdown or quotes.
3. For open-ended questions (textareas, bios, explanations, rationale):
   - ${styleGuidance}
   - Write with natural human variation: mix shorter sentences with occasional longer ones.
   - Do not use textbook transitions like "First and foremost" or "In addition".
   - Sound like a real person with genuine practical business experience, not an essayist.
4. Base your answers strictly on the user profile provided and any web research context.

User Profile:
${JSON.stringify(profile, null, 2)}

Web Research Context (from Tavily):
${JSON.stringify(researchFindings, null, 2)}

Output format: You MUST return a strictly valid JSON object mapping each form field ID or name to its filled value.
Example format:
{
  "fields": {
    "first_name": "Alex",
    "last_name": "Morgan",
    "company": "Apex Innovations LLC",
    "loan_reason": "We are expanding inventory for Q3 fulfillment and onboarding two full-time operations leads."
  },
  "notes": "Verified against corporate profile and Tavily lookup."
}`;
}

/**
 * Call Groq / Grok API with the form fields and humanizer prompt
 */
async function generateFieldValues(fields, profile, researchFindings = null, userApiKey = null, userSettings = {}) {
  // Determine if using Groq (gsk_...) or Grok (xai-...) or server configured keys
  const providedKey = userApiKey || userSettings.grokApiKey || userSettings.groqApiKey;
  let apiKey = providedKey || config.GROQ_API_KEY || config.GROK_API_KEY;
  
  let apiUrl = config.GROQ_API_URL;
  let model = 'openai/gpt-oss-120b';

  if (apiKey && apiKey.startsWith('gsk_')) {
    apiUrl = config.GROQ_API_URL;
    model = userSettings.defaultModel && !userSettings.defaultModel.includes('grok') ? userSettings.defaultModel : 'openai/gpt-oss-120b';
  } else if (apiKey && (apiKey.startsWith('xai-') || userSettings.provider === 'grok')) {
    apiUrl = config.GROK_API_URL;
    model = 'grok-2-latest';
  } else if (config.GROQ_API_KEY) {
    apiKey = config.GROQ_API_KEY;
    apiUrl = config.GROQ_API_URL;
    model = 'openai/gpt-oss-120b';
  }

  const toneStyle = profile.humanizerStyle || 'direct_natural';

  if (!apiKey) {
    console.warn('[LLM Engine] No Groq or Grok API key available. Using built-in humanizer heuristic generator.');
    return simulateHumanizedFill(fields, profile, researchFindings);
  }

  const systemPrompt = buildHumanizerSystemPrompt(profile, researchFindings, toneStyle);

  const userPrompt = `Please fill out the following form fields realistically and naturally based on the master profile and research.

Form Fields to fill:
${JSON.stringify(fields, null, 2)}

Return strictly valid JSON with the structure:
{
  "fields": {
    "<field_id_or_name>": "<filled_value>"
  },
  "notes": "<brief note on inferred values>"
}`;

  try {
    const isGroq = apiUrl.includes('groq.com');
    console.log(`[LLM Engine] Calling ${isGroq ? 'Groq LPU' : 'xAI Grok'} with model ${model}...`);

    const response = await axios.post(
      apiUrl,
      {
        model: model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.65,
        response_format: { type: 'json_object' }
      },
      {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        },
        timeout: 25000
      }
    );

    const content = response.data.choices[0].message.content;
    let parsed;
    try {
      parsed = JSON.parse(content);
    } catch (e) {
      const clean = content.replace(/```json/g, '').replace(/```/g, '').trim();
      parsed = JSON.parse(clean);
    }

    const rawFields = parsed.fields || parsed;
    // Post-process to audit against robotic cliches
    const auditedFields = auditAndCleanFields(rawFields);

    return {
      success: true,
      fields: auditedFields,
      notes: parsed.notes || `Generated using ${isGroq ? 'Groq LPU (Llama 3.3)' : 'Grok 2'} humanizer engine.`,
      modelUsed: model,
      provider: isGroq ? 'Groq LPU' : 'xAI Grok',
      source: 'live_llm'
    };
  } catch (error) {
    console.error('[LLM API Error]:', error.response?.data || error.message);
    return {
      success: false,
      error: error.response?.data?.error?.message || error.message,
      fallbackUsed: true,
      ...simulateHumanizedFill(fields, profile, researchFindings)
    };
  }
}

/**
 * Filter out robotic clichés if any slip through
 */
function auditAndCleanFields(fields) {
  const cleaned = { ...fields };
  for (const key of Object.keys(cleaned)) {
    if (typeof cleaned[key] === 'string') {
      let val = cleaned[key];
      for (const banned of BANNED_AI_WORDS) {
        const regex = new RegExp(`\\b${banned}\\b`, 'gi');
        val = val.replace(regex, '');
      }
      cleaned[key] = val.replace(/\s{2,}/g, ' ').trim();
    }
  }
  return cleaned;
}

/**
 * Smart humanizer heuristic simulator fallback
 */
function simulateHumanizedFill(fields, profile, researchFindings) {
  const result = {};

  const p = profile || {};
  const nameParts = (p.fullName || 'Alex Morgan').split(' ');
  const firstName = nameParts[0] || 'Alex';
  const lastName = nameParts.slice(1).join(' ') || 'Morgan';

  fields.forEach(f => {
    const key = f.id || f.name || f.label || 'field';
    const label = (f.label || f.name || f.placeholder || f.id || '').toLowerCase();
    const type = (f.type || 'text').toLowerCase();

    if (label.includes('first') && label.includes('name')) {
      result[key] = firstName;
    } else if (label.includes('last') && label.includes('name')) {
      result[key] = lastName;
    } else if (label.includes('full') && label.includes('name') || label === 'name') {
      result[key] = p.fullName || `${firstName} ${lastName}`;
    } else if (label.includes('email') || type === 'email') {
      result[key] = p.email || 'alex.morgan@apexinnovations.example.com';
    } else if (label.includes('phone') || label.includes('tel') || type === 'tel') {
      result[key] = p.phone || '+1 (555) 234-8901';
    } else if (label.includes('company') || label.includes('business') || label.includes('organization')) {
      result[key] = p.companyName || 'Apex Innovations LLC';
    } else if (label.includes('website') || label.includes('url')) {
      result[key] = p.companyWebsite || 'https://apexinnovations.example.com';
    } else if (label.includes('title') || label.includes('position') || label.includes('role')) {
      result[key] = p.jobTitle || 'Managing Director';
    } else if (label.includes('tax') || label.includes('ein') || label.includes('tin')) {
      result[key] = p.taxIdEin || '12-3456789';
    } else if (label.includes('revenue') || label.includes('annual') || label.includes('income')) {
      result[key] = p.annualRevenue || '$1,250,000';
    } else if (label.includes('address') || label.includes('street')) {
      result[key] = p.address || '450 Lexington Ave, Suite 1200';
    } else if (label.includes('city')) {
      result[key] = p.city || 'New York';
    } else if (label.includes('state') || label.includes('province')) {
      result[key] = p.state || 'NY';
    } else if (label.includes('zip') || label.includes('postal')) {
      result[key] = p.zipCode || '10017';
    } else if (label.includes('country')) {
      result[key] = p.country || 'United States';
    } else if (label.includes('industry')) {
      result[key] = p.industry || 'Financial Services';
    } else if (label.includes('reason') || label.includes('purpose') || label.includes('description') || type === 'textarea') {
      result[key] = 'Securing flexible commercial credit to finance upfront supplier purchase orders and expand warehousing capacity for upcoming contract cycles.';
    } else if (label.includes('experience') || label.includes('background') || label.includes('bio')) {
      result[key] = p.bio || 'Experienced commercial operator with over a decade managing supply chain logistics and technology infrastructure.';
    } else if (type === 'number') {
      result[key] = '75000';
    } else if (type === 'checkbox') {
      result[key] = true;
    } else if (f.options && f.options.length > 0) {
      result[key] = f.options[0].value || f.options[0].text || f.options[0];
    } else {
      result[key] = `${label ? label.charAt(0).toUpperCase() + label.slice(1) : 'Direct'} Entry`;
    }
  });

  return {
    success: true,
    fields: result,
    notes: 'Generated using persona matching with anti-AI cadence rules.',
    modelUsed: 'heuristic-humanizer',
    source: 'simulated_llm'
  };
}

module.exports = {
  generateFieldValues,
  auditAndCleanFields,
  BANNED_AI_WORDS
};
